# ----------------------------------------------------------------------------
#
# Package             : pyparsing.py
# Source Repo         : https://github.com/pyparsing/pyparsing
# Travis Job Link     : https://travis-ci.com/github/santosh653/pyparsing
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python

dist: xenial

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
      arch: amd64
    - python: 3.6
      env: TOXENV=py36
      arch: amd64
    - python: 3.7
      env: TOXENV=py37
      arch: amd64
    - python: 3.8
      env: TOXENV=py38
      arch: amd64
    - python: 3.9
      env: TOXENV=py39
      arch: amd64
    - python: pypy3
      env: TOXENV=pypy3
      arch: amd64
    - python: 3.5
      env: TOXENV=py35
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37
      arch: ppc64le
    - python: 3.8
      env: TOXENV=py38
      arch: ppc64le
    - python: 3.9
      env: TOXENV=py39
      arch: ppc64le
  fast_finish: true

install:
  - pip install tox codecov

script:
 - tox

after_success:
  - codecov
